---

- hosts: all
#  connection: local # 只针对本机链接模式

  tasks:
    - name: ok-task
      shell: echo "1" && echo "2"

    - name: skipping-task
      ansible.builtin.shell: echo "'{{ foo }}'"
      when: foo is defined

    - name: failing-task
      shell: exit -1
      ignore_errors: true

    - name: failing-task-when
      command: /usr/bin/ls /tmp/foobar.baz
      register: command_result
      failed_when: "'No such file or directory' in command_result.stderr"