---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: centos-deployment
spec:
  selector:
    matchLabels:
      app: centos
  replicas: 1
  template:
    metadata:
      labels:
        app: centos
    spec:
      containers:
        - name: centos-ssh
          image: harbor.dev.21vianet.com/taojun/centos:7.4.1708-ssh
          ports:
            - containerPort: 22
---
apiVersion: v1
kind: Service
metadata:
  name: centos-svc
spec:
  selector:
    app: centos
  type: NodePort
  ports:
    - protocol: TCP
      port: 22
      targetPort: 22