{{- if and .Values.prometheus.enabled .Values.prometheus.additionalConfigs }}
apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ template "kube-prometheus-stack.fullname" . }}
  namespace: {{ .Release.Namespace }}
data:
{{- range $key, $val := .Values.prometheus.additionalConfigs }}
  {{ $key }}: |-
{{ $val | indent 4}}
{{- end }}
{{- end -}}