apiVersion: webapp.demo2.com/v1
kind: Guestbook
metadata:
  name: guestbook-sample
#  namespace: demo2-operator-system
spec:
  # TODO(user): Add fields here
  # Add fields here
  image: harbor.dev.21vianet.com/taojun/nginx:1.18
  port: 80
  pushPort: 30003
  singlePodQPS: 500
#  totalQPS: 600
