apiVersion: v1
kind: Service
metadata:
  name: prometheus-k8s-sidecar-0
  namespace: monitoring
spec:
  ports:
    - name: web
      port: 10902
      protocol: TCP
      targetPort: http
    - name: grpc
      port: 10901
      protocol: TCP
      targetPort: grpc
  selector:
    app: prometheus
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: kube-prometheus
    prometheus: k8s
    statefulset.kubernetes.io/pod-name: prometheus-k8s-0
  sessionAffinity: ClientIP
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-k8s-sidecar-1
  namespace: monitoring
spec:
  ports:
    - name: web
      port: 10902
      protocol: TCP
      targetPort: http
    - name: grpc
      port: 10901
      protocol: TCP
      targetPort: grpc
  selector:
    app: prometheus
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: kube-prometheus
    prometheus: k8s
    statefulset.kubernetes.io/pod-name: prometheus-k8s-1
  sessionAffinity: ClientIP
  type: NodePort
